### ISSUE TITLE
Cannot find module '@aws-sdk/client-s3'

### ISSUE THREAD

**Issue by oieduardorabelo** [jeremydaly/lambda-api#229]
hey folks 👋 , after migrating to v1, when running unit tests with `lambda-api` I see:

```
  Cannot find module '@aws-sdk/client-s3' from 'node_modules/lambda-api/lib/s3-service.js'
```

Based on the changelog:
https://github.com/jeremydaly/lambda-api/compare/v0.12.0...v1.0.0

These dependencies should be either `peerDependencies` or `dependencies` and not `devDependencies`?

**Comment by oieduardorabelo** [comment]
btw, I do use AWS SDK v3 in my application, with `@aws-sdk/client-dynamodb`, but no S3 client.

**Comment by naorpeled** [comment]
Hey @oieduardorabelo,
good point,
wanna make a PR for it?

I unfortunately won't be near a computer until Sunday probably

**Comment by oieduardorabelo** [comment]
Closing this issue, it was fixed in the main branch by these PRs:

https://github.com/jeremydaly/lambda-api/pull/232
https://github.com/jeremydaly/lambda-api/pull/231
